### ISSUE TITLE
Load and run has different results than if you go through manually

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#127]
Something I noticed the other day when crunching data. The differences start with aggregated proteoforms. The values in the method file are matching the default parameter values in the program if nothing is changed, or seem to be, so I dont think that's the issue. Has anyone else noticed this? I'm looking at Results Summary, which is how I noticed.

**Comment by lschaffer2** [comment]
I found the issue, will commit changes.

**Comment by acesnik** [comment]
Nice!

On Tuesday, June 28, 2016, Leah Schaffer <notifications@github.com> wrote:

> I found the issue, will commit changes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/smith-chem-wisc/proteoform-suite/issues/127#issuecomment-229111142>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APlfp9_ASr3pjUv_8DmClfqrSIFk782dks5qQVGIgaJpZM4I-Img>
> .
>


-- 

Anthony Cesnik
L.M. Smith Group
Department of Chemistry
University of Wisconsin - Madison
acesnik@chem.wisc.edu

--
