### ISSUE TITLE
Parallels/old data structure

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#159]
The pull request I just made has matching # neucode pairs, agg proteoforms, ET pairs/peaks, and EE pairs/peaks with the old proteoform suite for the "Auto-short" excel file in Examples. To accomplish this, I had to comment out all of the parallel loops. These were causing a different result every time I ran the program, which doesn't make sense... 

For now, I went through testing parallel forloops and if it was changing the result (for anything, even by a tiny amount) between different runs, it's commented out with //PARALLEL PROBLEM above so we can easily find the ones not working and fix them. 

I just noticed now, however, that with a larger and larger files, there is an increase in the difference for each module between new/old PS. Once the ET and EE dgvs are more informative about what's in each pair, we can check what is not being included/see why. It is something to keep in mind though, moving forward.

**Comment by lschaffer2** [comment]
The issues in differences between new/old PS seems to be fixed now for larger files, after finding some small issues in both the new/old. Now, just fixing parallelization is the issue. 

Side note: in the time it took to load raw exp components in the old way, I could run through every module in the new way :)

**Comment by acesnik** [comment]
Thanks for the update, Leah. I'm glad to hear those issues are resolved and that it's faster!
