### ISSUE TITLE
"Identified Proteoforms" count

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#188]
Just wanted to flag this code: does it provide us with the number of "identified proteoforms?" It is counting the number of relations in the peaks that have been accepted, but it seems like that's different than the number of identified proteoforms.

`tb_IdentifiedProteoforms.Text = big_peaks.Select(p => p.mass_difference_group.Count).Sum().ToString();`

**Comment by trishorts** [comment]
In ET, each proteoform relation is between a single aggregate proteoform is connected to a single theoretical proteoform. I take one aggregated proteoform simply to be a collection of observations of the same thing. Ergo, a count of relations should equal a count of identified proteoforms.

Now, if this is in EE, then we have identifed "nothing". We should be counting the unique set of all aggregated proteoform relations that are contained in the accepted peaks.

**Comment by acesnik** [comment]
Fixed in https://github.com/smith-chem-wisc/proteoform-suite/pull/312. Instead of "Identified Proteoforms," the EE form now says "Accepted Relations."
