### ISSUE TITLE
Identical-mass EE relations

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#196]
Consider we have two ExperimentalProteoforms with identical masses. We're missing relations with that case right now because we're not allowing the masses to be equal:
List<ProteoformRelation> relations = new List<ProteoformRelation>(from pf1 in pfs1

from pf2 in pfs2

where pf1.modified_mass > pf2.modified_mass

where (!Lollipop.neucode_labeled || pf1.lysine_count == pf2.lysine_count)

where pf1.modified_mass - pf2.modified_mass <= Lollipop.ee_max_mass_difference

select new ProteoformRelation(pf1, pf2, relation_type, pf1.modified_mass - pf2.modified_mass)

);

I'm going to change the first where-clause to `where pf1.modified_mass >= pf2.modified_mass && pf1 != pf2` instead to allow for this case, but also not allow self-comparisons by checking that the addresses for those objects are not equal.

**Comment by trishorts** [comment]
Two experimental proteoforms with exactly the same experimental mass should not exist. They should have been aggregated. Our big peak in EE at 0 is an aggregation failure. This could be dealt with by adding time component. Part of a bigger discussion and analysis.

**Comment by acesnik** [comment]
Glad to see the EE relations tightening up with your recent improvements, Michael!
