### ISSUE TITLE
theoretical database

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#233]
Have we considered loading in at the very least just paths to the xml/ptm list for creating the database? It makes loadandrun/open and save/run with presets difficult to stop in the middle if there isn't an xml/ptm list at whatever path.

**Comment by trishorts** [comment]
Put in a try catch block with prompt for path

On Oct 26, 2016 7:33 PM, Leah Schaffer <notifications@github.com> wrote:

Have we considered loading in at the very least just paths to the xml/ptm list for creating the database? It makes loadandrun/open and save/run with presets difficult to stop in the middle if there isn't an xml/ptm list at whatever path.

-

**Comment by lschaffer2** [comment]
That's what I meant by stop in the middle - it has to stop the running to ask (this only really matters for my label free several hour runs)-  but I thnik for now the setup w/ theo in the middle makes sense so never mind
