### ISSUE TITLE
separate module for TD/BU data

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#237]
Right now if you click an ET pair, it shows all the PSMs for td/bu data
MRS had the idea that it might be cool to have a separate page for this -- after ET maybe, we could have a list of all proteoforms that were in peaks above threshold, as well as all proteoforms (or proteins for BU) seen in BU/TD data grouped by accession. I was thinking of having a string in a tb of the protein sequence, with different colors based on PTMs observed at those amino acids, or colors for the sequences seen in BU/TD fragments. I don't think this should be too difficult (famous last words)  

Also to do is to switch the BU read in from the Morpheus PSMs to the more general .pep file

**Comment by acesnik** [comment]
I'm tempted to say we should play with td/bu in a branch of your fork, and leave them out of upstream/master at this point, since they'll be going in a separate paper. We can finalize the structural changes and additional testing before submitting your publication.
