### ISSUE TITLE
ET Pairs crashes upon refreshing with decoy databases

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#262]
1. Created theoretical database with 10 decoy databases.
2. Went to ET Pairs page, and it automatically generated ET Pairs with FDRs, even if ET Pairs were already generated.
3. Hit refresh, and the FDRs change. 
4. Hit refresh again, and the program crashed.

**Comment by lschaffer2** [comment]
I can look at this today, along with another few issues I've encountered. One thing is if you go to any page, it reruns the program even if it's already been run before (#2 on this) instead of just running it the first time.

**Comment by lschaffer2** [comment]
This should be fixed - had to clear all decoys' relations properly when running the gamut... let me know if it doesn't work for you still.
