### ISSUE TITLE
permutation tests are calculated incorrectly

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/proteoform-suite#264]
my bad.

**Comment by acesnik** [comment]
Haha, shoot. How so?

**Comment by trishorts** [comment]
complicated......but I know what to do. just not how to do it yet...You can thank KB

**Comment by acesnik** [comment]
Resolved with @trishorts's rewrite of permutation analysis based on Tusher & Tibshriani's paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33173/pdf/pq005116.pdf
