### ISSUE TITLE
error in ExperimentExperimentComparison.cs "updateFiguresOfMerit()

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/proteoform-suite#265]
ran into a case where big_peaks was empty. Apparently there were no "accepted". perhaps because I didn't have a decoy database.

**Comment by lschaffer2** [comment]
EE fdr isn't set with a decoy, it depends on the false relations. I checked to make sure there were accepted peaks before setting the fdr. will commit change shortly
