### ISSUE TITLE
ET Peaks Selection Auto Sorting

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/proteoform-suite#301]
When sorting the ET list according to delta mass, and selecting a value, the list goes back and sorts according to peak center count automatically. It would be more convenient if this does not happen.

**Comment by acesnik** [comment]
Okay, thanks for letting me know!

**Comment by acesnik** [comment]
I can't reproduce this error.

**Comment by lschaffer2** [comment]
The peak list doesn't resort - the relations DGV resorts when you click a peak in the peak list. I'll try to fix this

**Comment by lschaffer2** [comment]
solved in #320
