### ISSUE TITLE
Maintain peak list sorting when manually accepting peaks

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#324]
Currently, the list is repopulated and reordered. Do we need to redraw the peak list datagridview upon changing a cell? If so, is there a way we could maintain the ordering?

**Comment by lschaffer2** [comment]
I've found dgv.refresh() to work for this

**Comment by acesnik** [comment]
Could you take care of this in #320 ?

**Comment by lschaffer2** [comment]
I did for ET and EE. Is there anywhere else it's needed?
