### ISSUE TITLE
Expand results summary

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#329]

**Comment by acesnik** [comment]
* Automatically save cytoscape scripts with descriptive filenames with results dump
* Include a final results table with information for collaborators

**Comment by lschaffer2** [comment]
**Accepted ** neucode pairs
**Accepted** experimental proteoforms
ET pairs in accepted peaks
Accepted ET peaks
EE pairs in accepted peak
Accepted EE peaks
Proteoforms in ambiguous families
Proteoforms in identified families
Proteoforms in unidentified families
 Orphans
