### ISSUE TITLE
Improve automatic experimental assignments

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#337]
1. Only allow missing amino acids if at the ends of the sequence; check for successive degradation
2. Apply Occam's Razor to ET assignments. While a large PTM set derived from GPTMD may be closer to the observed mass, the simplest explanation within mass tolerance should be taken.
3. Perhaps score modifications based on their frequency of appearance in the GPTMD database to prioritize the most common ones as more likely in 2).

**Comment by lschaffer2** [comment]
4. PTM masses should be directional, get rid of negative or positive mass differences that don't make sense (Ex: get rid of EE relations where it's -42.01 off of unmodified)

**Comment by acesnik** [comment]
Implemented in https://github.com/smith-chem-wisc/proteoform-suite/pull/348

**Comment by acesnik** [comment]
Resolved all but 4 (see issue https://github.com/smith-chem-wisc/proteoform-suite/issues/350)
