### ISSUE TITLE
No node coloring when building selected families in Cytoscape

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/proteoform-suite#339]
Building all families works fine, but when building selected families, all nodes have the same color.
![selected families cytoscape](https://cloud.githubusercontent.com/assets/20566230/24419801/069dfd74-13b6-11e7-89ad-a0fcda11bb0f.png)

**Comment by acesnik** [comment]
This usually happens when the style isn't loaded properly, a Cytoscape problem instead of a ProteoformSuite one. Check that the style you generated is selected under the style tab in Cytoscape. Looks like it's "default" right now, but the title should match your network title.

**Comment by acesnik** [comment]
I think I figured out a hackish method to make applying the style more consistent with the script., and I'll include it in the next release. Thanks again for reporting!
