### ISSUE TITLE
Store modification lists that should be used for proteoform ID assignment

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#340]
We should have a default ptmlist stored like Metamorpheus does. If you don't use GPTMD, then the uniprot ptmlist is missing oxidaiton, ammonia loss, etc so it's affecting the automatic experimental identification. -17.03 was labeled as oxobutanoic acid instead of ammonia loss (?) We could also code these super common PTMs in if we're worried about ptmlist clashing.

**Comment by acesnik** [comment]
Check out the ptmlists in the Mods folder of proteoform suite. The "Unlocalized" modification type tag is prioritized in assigning experimentals. I'd recommend including those as ptmlists for now.

**Comment by acesnik** [comment]
See https://github.com/smith-chem-wisc/proteoform-suite/tree/master/Mods

**Comment by lschaffer2** [comment]
I see. Do you think these should be read in automatically, or are you importing them with your ptmlist?

**Comment by acesnik** [comment]
I'm just reading them with the other ptmlists. Not sure if they should be read automatically, but perhaps.

**Comment by lschaffer2** [comment]
I think automatic reading would make sense, and having the lists kept with proteoformsuite. That way we can update them as we go, and we're all using the same lists.
