### ISSUE TITLE
GUI header issue when returning to Load deconvolution results page

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#341]
![image](https://cloud.githubusercontent.com/assets/16846041/24529223/0bc205e6-1570-11e7-9488-9d8d0f62dece.png)

**Comment by acesnik** [comment]
Is this in your top-down branch? I wonder if one of the settings didn't get transferred. It's something like "show combo box" that you have to disable in the properties of the form.

**Comment by lschaffer2** [comment]
Yes it is my td branch. Is it for the DGV combo boxes?

**Comment by lschaffer2** [comment]
Found it, thanks!!
