### ISSUE TITLE
Losing E-T pairs after switching analysis from UniProt to G-PTM-D database

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/proteoform-suite#345]
With my E. coli data, 16 selected E-T pairs in the UniProt analysis disappeared in the G-PTM-D analysis. In 11 of the 16 cases, Proteoform Suite paired the original experimental with a new theoretical of the same gene name, but with PTM(s) (found in the bottom-up data). The PTM(s) had a sum of mass difference lower than the previous E-T mass difference, making it more susceptible to be paired with the original experimental proteoform. The new mass difference thus became a random number, and were not selected. This issue creates several different scenarios:

1. The experimental proteoform still made into the same family using E-E connections. The new suggested PTM was different from the previous E-T correspondence, and seemed unlikely.

2. The experimental proteoform still made into the same family using E-E connections. The new suggested PTM was different from the previous E-T correspondence, but was likely, undermining the previous E-T connection.

3. The experimental proteoform still made into the same family using E-E connections. The new suggested PTM was the same as the previous E-T correspondence. 

4. The experimental proteoform became an orphan or a member in an un-identified family.

See attached spreadsheet for details of each case.
[The Lost E-T Pairs (4-3).xlsx](https://github.com/smith-chem-wisc/proteoform-suite/files/895255/The.Lost.E-T.Pairs.4-3.xlsx)

**Comment by acesnik** [comment]
Thanks for the hard work to find these issues Sean. I'm deep in the weeds trying to improve the accuracy of ET relations and other aspects of proteoform identification (see https://github.com/smith-chem-wisc/proteoform-suite/issues/337). Your annotated examples will be a great way to check whether my additions work to improve the results.

**Comment by acesnik** [comment]
I figured out a better solution for picking the best ET pair for each experimental. It'll be in the next update.

**Comment by acesnik** [comment]
Addressed in https://github.com/smith-chem-wisc/proteoform-suite/pull/348, but it would be nice to double check that it solved your issues.
