### ISSUE TITLE
Allow for +- one missed monoisotopic in experimental identification

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#349]
Will likely be need for unlabeled data or many peaks would be missed

**Comment by acesnik** [comment]
This makes me nervous for EE because we are looking for up to 3 missed monoisotopics with a 5 PPM mass tolerance around the aggregated mass. I would want to see some proof that we are aggregating around the wrong monoisotopic in some (or many) instances. If we could solve the problem at the level of aggregation, that would improve the program more than looking for more missed monoisotopics at the level of identification.

**Comment by acesnik** [comment]
I am less confident in identifications including a missed monoisotopic than ones without. But that said, I think you could implement this fairly easily by including it as an unlocalized modification in the intact_mods.txt file. We should have some way of deselecting it for the run on the load_results page.

**Comment by lschaffer2** [comment]
We are looking up to 3, but sometimes I wonder if we might still shift at times off by one, say the intensities are close for both but the wrong one is slightly higher. Or for ones where all of the intensities are low. In ET for unlabeled, calibrated data I have a large peak right at -1.0023. I can shift these but I think it does show we get it wrong sometimes. Also cases where there's only a few observations, and they're all off by one. I could look into that -1 peak in ET and see what's up with those.

**Comment by acesnik** [comment]
I might try this out, now. I'm going to weight it with the third_quartile rank, so it might occur with unmodified and oxidation, but not with others. The -15, -16, -17 mess shouldn't be a problem because I'm penalizing additional modifications, e.g. a missed monoisotopic.

**Comment by lschaffer2** [comment]
Definitely in ET though we should look at plus and minus one from unmodified or these relations won't be added

**Comment by lschaffer2** [comment]
In EE, maybe we could treat missed mono's differently -- do a first pass identification, then in the second pass look for them and see how if they fit into the current identifications properly or identify additional ones - if so, then we know which E mass to shift.

**Comment by acesnik** [comment]
It still makes me nervous, but I think the ranking system will prevent it from becoming a mess.

**Comment by acesnik** [comment]
Hmm, I implemented this, but I really don't have a good example to check whether it's working well other than to say I'm not seeing it, which is probably a good sign for the negative side! I'll commit it and leave it in for now.

**Comment by lschaffer2** [comment]
Awesome, I'll check with some unlabeled data and will let you know if it identifies correctly or if I see problems introduced.

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/proteoform-suite/pull/348
