### ISSUE TITLE
Make sure everything has been loaded in before allowing user to proceed

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#357]
I keep accidentally trying to do EE without a theoretical database loaded in which cases crashing (need ptmsets). It might  be a good idea to unenable all the results tabs until the user has loaded in at least one deconvolution results and a theoretical database
Also - are there checks in place to make sure that the database has the mod info at the top vs. needing a ptmlist.txt file? What happens if there's neither?

**Comment by acesnik** [comment]
I like allowing people to click on any tab they want to explore the application, even without data. I recommend we check whether data has been loaded.

**Comment by lschaffer2** [comment]
Yes that's true - I'll check for allpossibleptmsets to not be null on EE.

**Comment by acesnik** [comment]
Was this resolved in https://github.com/smith-chem-wisc/proteoform-suite/pull/356/files?

**Comment by lschaffer2** [comment]
Yes
