### ISSUE TITLE
Different results w/ same decoy databases

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#369]
I'm noticing different FDR's for my ET peaks if I run more than once with the same experimentals and databases. 
The problem only seems to occur with > 1 decoy database, so it perhaps has to do with how experiment-decoy is performed in parallel across databases.

**Comment by lschaffer2** [comment]
Getting rid of parallelforeach in relate_ed fixes it. Will be slower though :(

**Comment by acesnik** [comment]
Decoy databases are generated by shuffling sequence lengths, so I wouldn't expect the results to be exactly the same. Have you updated the relate method? It should all be in one method named relate().

**Comment by lschaffer2** [comment]
With the same decoy databases though - thye're only shuffled when they're created. Once created, relate_ed results should be the same

**Comment by acesnik** [comment]
Oh, that makes sense. Also, relate_ed() is definitely still a thing ...! 😅

**Comment by acesnik** [comment]
What if you lock the addition of the databases? 
`
Parallel.ForEach(decoy_proteoforms, decoys =>
{
     lock (ed_relations) ed_relations[decoys.Key] = relate(experimental_proteoforms, decoys.Value, ProteoformComparison.ExperimentalDecoy, true);
});

**Comment by lschaffer2** [comment]
I tried locking ed_relations when the decoy database set is added but still issues across ET comparisons... Must be something in relate() then that's not threadsafe

**Comment by acesnik** [comment]
Possibly during setting the FDR? There are a couple lines of code for calculating the EF/ED fdrs that you could try locking.

**Comment by acesnik** [comment]
Your relate_ed() fix works well! Including that in https://github.com/smith-chem-wisc/proteoform-suite/pull/370
