### ISSUE TITLE
Confusing load decon results page for 1st time users

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#372]
Rachel said because the "Clear" and "Full Automatic Run" buttons were so big, she thought she had to run through that way. We may want to make it more clear that you need to step through everything under the results tab -- maybe bring back that First times user page with those buttons so if you do click on of those buttons, it shows the instructions.
I can see why this might be unclear to people because other software packages that have you load in all your data have a specific "Go" button, whereas we click through all the tabs in order to have it analyze data.

**Comment by acesnik** [comment]
I think this would be ameliorated by a tutorial video, which we are planning. Thanks for posting her feedback!

**Comment by lschaffer2** [comment]
Maybe we could bold the results tab or make it a different color (something to do with candy or proteoforms) to emphasize this is where you click, over File/Method?

**Comment by acesnik** [comment]
Done in https://github.com/smith-chem-wisc/proteoform-suite/pull/374
