### ISSUE TITLE
Make heuristics for identification customizable in ProteoformFamilies

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#377]
I have had to redo the heuristics for identifying proteoforms when switching databases, which takes time and access to the code. Let's think about how best to make this more interactive and flexible.
* Additional PTM penalty -- was using first_quartile / 2 before; now using 1
* Modification rank of phospho -- was letting the frequency in the database determine this, but I had to add it as an unlocalized mod to get a boost there
* Ranks for "unlocalized," "fatty acid" and other mod types are hard coded now. In addition to the ranks for modification masses, we should allow users to set custom priorities for specific mod types. If they don't specify anything, we'll pick a rank based on the database.

**Comment by lschaffer2** [comment]
We could show the three rank lists in textboxes, and you could select to move certain PTMs to different ranks if they're not in the correct box.

**Comment by lschaffer2** [comment]
On lower right hand corner of theortetical database, could put four list  boxes, high, medium, low, and no frequency. Within each then they are ranked highest to lowest within that rank, user can move them up and down or across list boxes

**Comment by acesnik** [comment]
This could be built into UnlocalizedModification to allow some customization.

**Comment by acesnik** [comment]
Addressed in https://github.com/smith-chem-wisc/proteoform-suite/pull/399
