### ISSUE TITLE
GUI forms on small screens

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#422]
This is theoretical database on my laptop: there's no way to access the button at the bottom... seems like there should be a way to lock the placement of buttons, etc and then have scroll bars
![image](https://user-images.githubusercontent.com/16846041/28420582-328aa6f0-6d28-11e7-8cb1-ad3a708e8b53.png)

**Comment by acesnik** [comment]
Thanks for the note! We can fix this issue by putting the form items in split containers.

**Comment by acesnik** [comment]
Just took care of this. It'll be in my next pull request.

**Comment by acesnik** [comment]
fixed in https://github.com/smith-chem-wisc/proteoform-suite/pull/426
